//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eAMS.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROP_MNGEntities : DbContext
    {
        private const string connectionString = "name=PROP_MNGEntities";

        public PROP_MNGEntities()
            : base(connectionString)
        {
        }

        //Data Source = SERVER; Initial Catalog = DATABASE; Persist Security Info=True;User ID = USERNAME; Password=PASSWORD;MultipleActiveResultSets=True
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PropMaint> PropMaints { get; set; }
        public virtual DbSet<PropRegi> PropRegis { get; set; }
    }
}
